# All paths are relative to the config file location or the project root location

# Files with access details for zerodha api
access_files:
  api_one: database.ini
  api_two: database_hemant.ini
  api_three: database_pettem.ini
  api_four: database_amit.ini
  api_five: database_rupinder.ini


# Location of the cache files for ticks data
cache_files:
  prev_timestamp_1: temp_cache/prev_timestamp_1.txt
  prev_timestamp_2: temp_cache\prev_timestamp_2.txt
  prev_timestamp_3: temp_cache\prev_timestamp_3txt
  prev_timestamp_4: temp_cache\prev_timestamp_4.txt
  prev_timestamp_5: temp_cache\prev_timestamp_5.txt
  prev_timestamp_6: temp_cache\prev_timestamp_6.txt
  prev_1: temp_cache/prev_1.txt
  prev_2: temp_cache\prev_2.txt
  prev_3: temp_cache\prev_3.txt
  prev_4: temp_cache\prev_4.txt
  prev_5: temp_cache\prev_5.txt
  prev_6: temp_cache\prev_6.txt



# Rabbitmq config details
rabbitmq:
  username: guest
  password: guest
  host: localhost
  port: 5672
  queues:
    banknifty: banknifty


zerodha:
  kite_trade_url: "https://kite.trade/connect/login?api_key="


start_connection:
  currency:
    hour: 9
    minute: 0
    second: 0
  stock:
    hour: 9
    minute: 15
    second: 0

end_connection:
  currency:
    hour: 17
    minute: 0
    second: 0
  stock:
    hour: 15
    minute: 30
    second: 0     

crosscheck_file_location: crosscheck_files/